(require 'moe-theme)
(load-theme 'zenburn t)

(defun zb ()
  (interactive)
  (disable-theme 'adwaita)
  (disable-theme 'twilight)
  (disable-theme 'deeper-blue)
  (disable-theme 'moe-light)
  (disable-theme 'moe-dark)
  (load-theme 'zenburn t))

(defun tw ()
  (interactive)
  (disable-theme 'adwaita)
  (disable-theme 'zenburn)
  (disable-theme 'deeper-blue)
  (disable-theme 'moe-light)
  (disable-theme 'moe-dark)
  (load-theme 'twilight t))

(defun aw ()
  (interactive)
  (disable-theme 'zenburn)
  (disable-theme 'twilight)
  (disable-theme 'deeper-blue)
  (disable-theme 'moe-light)
  (disable-theme 'moe-dark)
  (load-theme 'adwaita t))

(defun db ()
  (interactive)
  (disable-theme 'adwaita)
  (disable-theme 'zenburn)
  (disable-theme 'twilight)
  (disable-theme 'moe-light)
  (disable-theme 'moe-dark)
  (load-theme 'deeper-blue t))

(defun md ()
  (interactive)
  (disable-theme 'adwaita)
  (disable-theme 'zenburn)
  (disable-theme 'twilight)
  (disable-theme 'deeper-blue)
  (disable-theme 'moe-light)
  (load-theme 'moe-dark t))

(defun ml ()
  (interactive)
  (disable-theme 'adwaita)
  (disable-theme 'zenburn)
  (disable-theme 'twilight)
  (disable-theme 'deeper-blue)
  (disable-theme 'moe-dark)
  (load-theme 'moe-light t))

(provide 'setup-themes)
